[package]
name = "rust_mermaid"
version = "0.1.0"
edition = "2021"
authors = ["Gioele SL Fierro <hck@gslf.it>"]
keywords = ["mermaidjs", "diagrams"]
categories = ["multimedia::images"]

[dependencies]
base64 = "0.21.2"
reqwest = {version = "0.11.18", features = ["blocking"]}
image = "0.24.6"

